# Generated by Django 4.1.7 on 2023-04-18 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Fargona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viloyat', models.CharField(max_length=50)),
                ('viloyat_haqida', models.TextField(max_length=700)),
                ('odamlar_soni', models.IntegerField()),
                ('ortacha_yosh', models.IntegerField()),
                ('tumanlar_soni', models.IntegerField()),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
            options={
                'verbose_name': "Farg'ona",
                'verbose_name_plural': "Farg'ona",
            },
        ),
        migrations.CreateModel(
            name='Namangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viloyat', models.CharField(max_length=60)),
                ('viloyat_haqida', models.TextField(max_length=700)),
                ('odam_soni', models.IntegerField()),
                ('ortacha_yosh', models.IntegerField()),
                ('tumanlar_soni', models.IntegerField()),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Namangan',
                'verbose_name_plural': 'Namangan qoshish',
            },
        ),
        migrations.CreateModel(
            name='WebSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=30)),
                ('age', models.IntegerField(default=20)),
            ],
            options={
                'verbose_name': 'WebSite',
                'verbose_name_plural': 'WebSite',
            },
        ),
        migrations.CreateModel(
            name='Createwebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(max_length=60)),
                ('website_date', models.DateField()),
                ('created_website', models.DateTimeField(auto_now_add=True)),
                ('create_website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.website')),
            ],
            options={
                'verbose_name': 'CreateWebSite',
                'verbose_name_plural': 'CreateWebSite',
            },
        ),
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('text', models.TextField(max_length=700)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.category')),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Card',
            },
        ),
    ]
