# Generated by Django 4.1.7 on 2023-04-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createwebsite',
            name='create_website',
        ),
        migrations.DeleteModel(
            name='Fargona',
        ),
        migrations.DeleteModel(
            name='Namangan',
        ),
        migrations.RemoveField(
            model_name='cards',
            name='category',
        ),
        migrations.AlterField(
            model_name='cards',
            name='heading',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Createwebsite',
        ),
        migrations.DeleteModel(
            name='WebSite',
        ),
    ]
