# Generated by Django 4.1.7 on 2023-04-19 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_createwebsite_create_website_delete_fargona_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cards',
            options={'verbose_name': 'Cards', 'verbose_name_plural': 'Cards'},
        ),
    ]
