# Generated by Django 4.1.7 on 2023-04-19 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_cards_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cards',
            options={},
        ),
    ]
