# Generated by Django 4.1.7 on 2023-04-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_cards_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fargona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viloyat', models.CharField(max_length=50)),
                ('viloyat_haqida', models.TextField(max_length=8700)),
                ('odamlar_soni', models.IntegerField()),
                ('ortacha_yosh', models.IntegerField()),
                ('tumanlar_soni', models.IntegerField()),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Fargona',
                'verbose_name_plural': 'Fargona',
            },
        ),
        migrations.AlterModelOptions(
            name='cards',
            options={'verbose_name': 'Cards', 'verbose_name_plural': 'Cards'},
        ),
    ]
