# Generated by Django 4.1.7 on 2023-04-20 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_foot_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Foot',
        ),
    ]
