# Generated by Django 4.1.7 on 2023-04-23 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_foot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foot',
            name='image',
        ),
        migrations.RemoveField(
            model_name='foot',
            name='text',
        ),
    ]
